### ISSUE TITLE
Add benchmark comparing to a gem with C extension, e.g. siong1987/yab62

### ISSUE THREAD

**Issue by rubyconvict** [steventen/base62-rb#2]

**Comment by steventen** [comment]
Hi @rubyconvict 

Thanks for your request. C extension gem has better performance over Ruby implementations in most of the cases. It's an unfair comparison.

One of the reasons to choose pure Ruby implementation is for better portability. e.g. you can use pure ruby code in CRuby, JRuby, or any other places. 

Also it's much easier for a Ruby developer to understand the code, and flexible to modify the code for their own use cases.

I still did a quick benchmark base on [this script](https://gist.github.com/siong1987/1369278) by the author of `yab62` just for curiosity. 

I'm using Ruby `2.3.1p112` on my 2.2 GHz Intel Core i7, 16GB macbook pro

And here are my results:
https://github.com/siong1987/yab62

```
0.310000   0.000000   0.310000 (  0.316373)
```

https://github.com/jtzemp/base62

```
7.330000   0.020000   7.350000 (  7.378888)
```

https://github.com/steventen/base62-rb

```
2.060000   0.010000   2.070000 (  2.075042)
```

As you can see, C extension one is clearly the winner. `base62-rb` is still a better pure Ruby implementation.

Benchmark code for `base62-rb`:

``` ruby
require 'benchmark'
require 'base62-rb'

time = Benchmark.measure do
  1_000_000.times do |i|
    encode = Base62.encode(i)
    decode = Base62.decode(encode)
    raise "Assertion error!" unless i == decode
  end
end

puts time
```

Thanks

**Comment by rubyconvict** [comment]
Thank you. Pure Ruby implementation is tempting, I will definitely give it a try.
